const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";

const MESSAGE_UPDATED = "MESSAGE_UPDATED";
const MESSAGE_DELETED = "MESSAGE_DELETED";

// Message read receipts
const MESSAGE_DELIVERED = "MESSAGE_DELIVERED";
const MESSAGE_SEEN = "MESSAGE_SEEN";

// Message reactions
const MESSAGE_REACTION_UPDATED = "MESSAGE_REACTION_UPDATED";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  MESSAGE_UPDATED,
  MESSAGE_DELETED,
  MESSAGE_DELIVERED,
  MESSAGE_SEEN,
  MESSAGE_REACTION_UPDATED,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
};
